package dev.gafipro.gafishader;

import com.mojang.brigadier.suggestion.Suggestions;
import com.mojang.brigadier.suggestion.SuggestionsBuilder;
import net.minecraft.command.CommandSource;
import net.minecraft.text.Text;

import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.Map;
import java.util.Set;
import java.util.concurrent.CompletableFuture;

public final class ComplementaryCatalog {
    private static final Map<String, String> GROUPS = new LinkedHashMap<>();
    private static final Set<String> OPTIONS = new LinkedHashSet<>();
    private static final Set<String> PROFILES = new LinkedHashSet<>(Arrays.asList(
            "POTATO", "VERYLOW", "LOW", "MEDIUM", "HIGH", "VERYHIGH", "ULTRA", "COMPLEMENTARY"
    ));

    static {
        GROUPS.put("performance", "SHADOW_QUALITY, shadowDistance, LIGHTSHAFT_QUALI_DEFINE, DETAIL_QUALITY, CLOUD_QUALITY, FXAA_DEFINE, SSAO_QUALI_DEFINE, ANISOTROPIC_FILTER, ENTITY_SHADOW, RAIN_PUDDLES, WATER_REFLECT_QUALITY, BLOCK_REFLECT_QUALITY, COLORED_LIGHTING, WORLD_SPACE_REFLECTIONS");
        GROUPS.put("camera", "BLOOM_ENABLED, BLOOM_STRENGTH, VIGNETTE_R, IMAGE_SHARPENING, UNDERWATER_DISTORTION, CHROMA_ABERRATION, MOTION_BLUR_EFFECT, MOTION_BLURRING_STRENGTH, LENSFLARE_MODE, LENSFLARE_I, DISTANT_LIGHT_BOKEH, TAA_DEFINE");
        GROUPS.put("atmosphere", "NIGHT_STAR_AMOUNT, AURORA_STYLE_DEFINE, AURORA_CONDITION, NIGHT_NEBULAE, NIGHT_NEBULA_I, RAINBOWS, RAINBOW_STYLE_DEFINE");
        GROUPS.put("clouds", "CLOUD_STYLE_DEFINE, CLOUD_ALT1, CLOUD_SPEED_MULT, CLOUD_CLOSED_AREA_CHECK, CLOUD_SHADOWS, CLOUD_R/G/B, CLOUD_UNBOUND_AMOUNT, CLOUD_UNBOUND_SIZE_MULT, CLOUD_UNBOUND_RAIN_ADD, DOUBLE_REIM_CLOUDS, CLOUD_ALT2");
        GROUPS.put("fog", "BORDER_FOG, CAVE_FOG, ATM_FOG_MULT, ATM_FOG_DISTANCE, ATM_FOG_ALTITUDE, LIGHTSHAFT_BEHAVIOUR, SPECIAL_PALE_GARDEN_LIGHTSHAFTS, LIGHTSHAFT_SMOKE, LIGHTSHAFT_SUNSET_SATURATION, LIGHTSHAFT_NOON_I, LIGHTSHAFT_SUNSET_I, LIGHTSHAFT_NIGHT_I, LIGHTSHAFT_RAIN_I");
        GROUPS.put("sunmoon", "SUN_MOON_STYLE_DEFINE, SUN_ANGLE, SUN_MOON_HORIZON, SUN_MOON_DURING_RAIN");
        GROUPS.put("weather", "RAIN_STYLE, SPECIAL_BIOME_WEATHER, WEATHER_TEX_OPACITY, IMPROVED_RAIN_DEFINE");
        GROUPS.put("water", "WATER_STYLE_DEFINE, WATER_CAUSTIC_STYLE_DEFINE, WATERCOLOR_MODE, BRIGHT_CAVE_WATER, WATER_ALPHA_MULT, WATER_FOG_MULT, WATER_FOAM_I, WATER_REFRACTION_INTENSITY, WAVING_WATER_VERTEX, WATER_BUMPINESS, WATER_BUMP_SMALL, WATER_BUMP_MED, WATER_BUMP_BIG, WATER_SPEED_MULT, WATER_SIZE_MULT");
        GROUPS.put("materials", "GENERATED_NORMALS, COATED_TEXTURES, GENERATED_NORMAL_MULT, COATED_TEXTURE_MULT, GENERATED_NORMAL_RES, ENTITY_GN_AND_CT, POM, POM_DEPTH, POM_QUALITY, POM_DISTANCE, POM_LIGHTING_MODE, POM_ALLOW_CUTOUT, DIRECTIONAL_BLOCKLIGHT, GLOWING_ORE_* , GLOWING_AMETHYST, GLOWING_LICHEN, EMISSIVE_REDSTONE_BLOCK, EMISSIVE_LAPIS_BLOCK, GLOWING_ARMOR_TRIM");
        GROUPS.put("lighting", "AMBIENT_MULT, CAVE_LIGHTING, SSAO_I, VANILLAAO_I, SHADOW_SMOOTHING, BLOCKLIGHT_FLICKERING, XLIGHT_I, XLIGHT_CURVE, HELD_LIGHTING_MODE, COLORED_LIGHT_SATURATION, COLORED_LIGHT_FOG, COLORED_LIGHT_FOG_I");
        GROUPS.put("dimensions", "NETHER_VIEW_LIMIT, NETHER_COLOR_MODE, NETHER_STORM, NETHER_STORM_I, NETHER_STORM_LOWER_ALT, NETHER_STORM_HEIGHT, END_BEAM_INTENSITY, END_STAR_INTENSITY, END_BEAM_CENTER_ALT, END_BEAM_HEIGHT, END_FLASHES");
        GROUPS.put("outlines", "SELECT_OUTLINE, SELECT_OUTLINE_I, SELECT_OUTLINE_R/G/B, SELECT_OUTLINE_AUTO_HIDE, WORLD_OUTLINE, WORLD_OUTLINE_THICKNESS, WORLD_OUTLINE_I, WORLD_OUTLINE_ON_ENTITIES, WORLD_OUTLINE_SCALED, DARK_OUTLINE, DARK_OUTLINE_THICKNESS");
        GROUPS.put("other", "SHOW_LIGHT_LEVEL, REDUCE_CLOSE_PARTICLES, LESS_LAVA_FOG, SNOWY_WORLD, HAND_SWAYING, COLOR_CODED_PROGRAMS, GLOWING_COLORED_PARTICLES, CONNECTED_GLASS_EFFECT, PORTAL_EDGE_EFFECT, PUDDLE_VOXELIZATION, COLORED_CANDLE_LIGHT");

        add(
                "SHADER_STYLE RP_MODE",
                "SHADOW_QUALITY shadowDistance LIGHTSHAFT_QUALI_DEFINE DETAIL_QUALITY CLOUD_QUALITY FXAA_DEFINE SSAO_QUALI_DEFINE ANISOTROPIC_FILTER ENTITY_SHADOW RAIN_PUDDLES WATER_REFLECT_QUALITY BLOCK_REFLECT_QUALITY COLORED_LIGHTING WORLD_SPACE_REFLECTIONS",
                "SPECIAL_PORTAL_EFFECTS REFLECTION_RES SKY_EFFECT_REFLECTION_DEFINE",
                "GENERATED_NORMALS COATED_TEXTURES GENERATED_NORMAL_MULT COATED_TEXTURE_MULT GENERATED_NORMAL_RES ENTITY_GN_AND_CT",
                "GLOWING_ORE_MASTER GLOWING_ORE_MULT GLOWING_ORE_IRON GLOWING_ORE_GOLD GLOWING_ORE_COPPER GLOWING_ORE_REDSTONE GLOWING_ORE_LAPIS GLOWING_ORE_EMERALD GLOWING_ORE_DIAMOND GLOWING_ORE_NETHERQUARTZ GLOWING_ORE_NETHERGOLD GLOWING_ORE_GILDEDBLACKSTONE GLOWING_ORE_ANCIENTDEBRIS GLOWING_ORE_MODDED",
                "GLOWING_AMETHYST GLOWING_LICHEN EMISSIVE_REDSTONE_BLOCK EMISSIVE_LAPIS_BLOCK GLOWING_ARMOR_TRIM",
                "IPBR_EMISSIVE_MODE IPBR_PARTICLE_FEATURES IPBR_COMPAT_MODE_DEFINE FANCY_GLASS MORE_REFLECTIVE_DISTANT_GLASS MIRROR_TINTED_GLASS GREEN_SCREEN_LIME HIDE_ARMOR",
                "NORMAL_MAP_STRENGTH CUSTOM_EMISSION_INTENSITY POM POM_DEPTH POM_QUALITY POM_DISTANCE POM_LIGHTING_MODE POM_ALLOW_CUTOUT DIRECTIONAL_BLOCKLIGHT",
                "WATER_STYLE_DEFINE WATER_CAUSTIC_STYLE_DEFINE WATERCOLOR_R WATERCOLOR_G WATERCOLOR_B UNDERWATERCOLOR_R UNDERWATERCOLOR_G UNDERWATERCOLOR_B WATERCOLOR_MODE BRIGHT_CAVE_WATER WATER_ALPHA_MULT WATER_FOG_MULT WATER_FOAM_I WATER_REFRACTION_INTENSITY WAVING_WATER_VERTEX WATER_BUMPINESS WATER_BUMP_SMALL WATER_BUMP_MED WATER_BUMP_BIG WATER_SPEED_MULT WATER_SIZE_MULT",
                "WAVING_FOLIAGE WAVING_LEAVES WAVING_WATER_VERTEX WAVING_LAVA WAVING_LILY_PAD WAVING_RAIN WAVING_SPEED WAVING_I NO_WAVING_INDOORS WAVING_I_RAIN_MULT",
                "BLOOM_ENABLED BLOOM_STRENGTH VIGNETTE_R IMAGE_SHARPENING UNDERWATER_DISTORTION CHROMA_ABERRATION MOTION_BLUR_EFFECT MOTION_BLURRING_STRENGTH LENSFLARE_MODE LENSFLARE_I DISTANT_LIGHT_BOKEH",
                "TM_EXPOSURE TM_CONTRAST T_SATURATION T_VIBRANCE TM_DARK_DESATURATION TM_WHITE_PATH COLORGRADING GR_RR GR_GR GR_RG GR_GG GR_RB GR_GB GR_BR GR_RC GR_BG GR_GC GR_BB GR_BC",
                "WORLD_BLUR WB_FOV_SCALED WB_CHROMATIC WB_ANAMORPHIC WB_DOF_I WB_DOF_FOCUS WB_DB_DAY_I WB_DB_NIGHT_I WB_DB_RAIN_I WB_DB_WATER_I WB_DB_NETHER_I WB_DB_END_I",
                "TAA_DEFINE TAA_SMOOTHING TAA_JITTER TAA_MOVEMENT_IMPROVEMENT_FILTER FXAA_STRENGTH FXAA_TAA_INTERACTION",
                "NIGHT_STAR_AMOUNT AURORA_STYLE_DEFINE AURORA_CONDITION NIGHT_NEBULAE NIGHT_NEBULA_I RAINBOWS RAINBOW_STYLE_DEFINE",
                "CLOUD_STYLE_DEFINE CLOUD_ALT1 CLOUD_SPEED_MULT CLOUD_CLOSED_AREA_CHECK CLOUD_SHADOWS CLOUD_R CLOUD_G CLOUD_B CLOUD_UNBOUND_AMOUNT CLOUD_UNBOUND_SIZE_MULT CLOUD_UNBOUND_RAIN_ADD DOUBLE_REIM_CLOUDS CLOUD_ALT2",
                "BORDER_FOG CAVE_FOG ATM_FOG_MULT ATM_FOG_DISTANCE ATM_FOG_ALTITUDE LIGHTSHAFT_BEHAVIOUR SPECIAL_PALE_GARDEN_LIGHTSHAFTS LIGHTSHAFT_SMOKE LIGHTSHAFT_SUNSET_SATURATION LIGHTSHAFT_NOON_I LIGHTSHAFT_SUNSET_I LIGHTSHAFT_NIGHT_I LIGHTSHAFT_RAIN_I",
                "SUN_MOON_STYLE_DEFINE SUN_ANGLE SUN_MOON_HORIZON SUN_MOON_DURING_RAIN",
                "NETHER_VIEW_LIMIT NETHER_COLOR_MODE NETHER_STORM NETHER_STORM_I NETHER_STORM_LOWER_ALT NETHER_STORM_HEIGHT",
                "END_BEAM_INTENSITY END_STAR_INTENSITY END_BEAM_CENTER_ALT END_BEAM_HEIGHT END_FLASHES",
                "RAIN_STYLE SPECIAL_BIOME_WEATHER WEATHER_TEX_OPACITY IMPROVED_RAIN_DEFINE",
                "ATM_COLOR_MULTS ATM_MORNING_R ATM_MORNING_G ATM_MORNING_B ATM_MORNING_I ATM_NOON_R ATM_NOON_G ATM_NOON_B ATM_NOON_I ATM_NIGHT_R ATM_NIGHT_G ATM_NIGHT_B ATM_NIGHT_I ATM_RAIN_R ATM_RAIN_G ATM_RAIN_B ATM_RAIN_I ATM_NETHER_R ATM_NETHER_G ATM_NETHER_B ATM_NETHER_I ATM_END_R ATM_END_G ATM_END_B ATM_END_I",
                "AMBIENT_MULT SHADOW_SMOOTHING CAVE_LIGHTING SSAO_I VANILLAAO_I PLAYER_SHADOW LEAF_SHADOW_OPTIMISATION_DEFINE",
                "LIGHT_COLOR_MULTS LIGHT_MORNING_R LIGHT_MORNING_G LIGHT_MORNING_B LIGHT_MORNING_I LIGHT_NOON_R LIGHT_NOON_G LIGHT_NOON_B LIGHT_NOON_I LIGHT_NIGHT_R LIGHT_NIGHT_G LIGHT_NIGHT_B LIGHT_NIGHT_I LIGHT_RAIN_R LIGHT_RAIN_G LIGHT_RAIN_B LIGHT_RAIN_I LIGHT_NETHER_R LIGHT_NETHER_G LIGHT_NETHER_B LIGHT_NETHER_I LIGHT_END_R LIGHT_END_G LIGHT_END_B LIGHT_END_I",
                "XLIGHT_I XLIGHT_CURVE HELD_LIGHTING_MODE BLOCKLIGHT_FLICKERING XLIGHT_R XLIGHT_G XLIGHT_B PIXELATED_SHADOWS PIXELATED_BLOCKLIGHT PIXELATED_AO PIXEL_SCALE",
                "SHOW_LIGHT_LEVEL REDUCE_CLOSE_PARTICLES LESS_LAVA_FOG SNOWY_WORLD HAND_SWAYING COLOR_CODED_PROGRAMS GLOWING_COLORED_PARTICLES",
                "SELECT_OUTLINE SELECT_OUTLINE_I SELECT_OUTLINE_R SELECT_OUTLINE_G SELECT_OUTLINE_B SELECT_OUTLINE_AUTO_HIDE",
                "WORLD_OUTLINE WORLD_OUTLINE_THICKNESS WORLD_OUTLINE_I WORLD_OUTLINE_ON_ENTITIES WORLD_OUTLINE_SCALED DARK_OUTLINE DARK_OUTLINE_THICKNESS",
                "MOON_PHASE_INF_LIGHT MOON_PHASE_INF_ATMOSPHERE MOON_PHASE_INF_REFLECTION MOON_PHASE_FULL MOON_PHASE_PARTIAL MOON_PHASE_DARK",
                "COLORED_LIGHT_SATURATION ACT_FIRE_COLOR_WARMNESS COLORED_LIGHT_FOG COLORED_LIGHT_FOG_I WORLD_SPACE_REFLECTIONS WORLD_SPACE_REF_MODE WORLD_SPACE_PLAYER_REF CONNECTED_GLASS_EFFECT PORTAL_EDGE_EFFECT PUDDLE_VOXELIZATION COLORED_CANDLE_LIGHT"
        );
    }

    private static void add(String... chunks) {
        for (String chunk : chunks) {
            for (String token : chunk.split("\\s+")) {
                if (!token.isBlank() && !token.startsWith("GLOWING_ORE_*")) OPTIONS.add(token);
            }
        }
    }

    public static CompletableFuture<Suggestions> optionSuggestions(SuggestionsBuilder builder) {
        return CommandSource.suggestMatching(OPTIONS, builder);
    }

    public static CompletableFuture<Suggestions> profileSuggestions(SuggestionsBuilder builder) {
        return CommandSource.suggestMatching(PROFILES, builder);
    }

    public static CompletableFuture<Suggestions> genericValueSuggestions(SuggestionsBuilder builder) {
        return CommandSource.suggestMatching(new String[]{
                "on", "off", "true", "false", "next", "previous",
                "0", "1", "2", "3", "4", "5", "10", "25", "50", "75", "100",
                "reimagined", "unbound", "after_rain", "always", "fullmoon", "snowy_biome"
        }, builder);
    }

    public static Set<String> optionNames() {
        return Set.copyOf(OPTIONS);
    }

    public static String helpText() {
        StringBuilder builder = new StringBuilder("Complementary Reimagined: " + OPTIONS.size() + " shader settings catalogued.");
        for (Map.Entry<String, String> entry : GROUPS.entrySet()) {
            builder.append("\n- ").append(entry.getKey()).append(": ").append(entry.getValue());
        }
        builder.append("\n\nUse /gafishader effect <option> <value> to change an option.");
        builder.append("\nBoolean shortcuts: on/off. Values not listed by the generic completion can still be entered manually.");
        builder.append("\nThe catalog is based on the current official Complementary Reimagined shaders.properties screen definitions.");
        return builder.toString();
    }

    public static Text groupText(String group) {
        String value = GROUPS.get(group.toLowerCase());
        if (value == null) return Text.literal("Grupo desconhecido. Usa /gafishader complementary");
        return Text.literal(group + ": " + value);
    }
}
